- name: Configure Proxmox host
  hosts: proxmox_hosts
  become: true
  vars_files:
    - ../config/infrastructure.yml
  roles:
    - host-config

# - name: Configure guest
#   hosts: proxmox_hosts
#   become: true
#   roles:
#     - guest-config